<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bantz</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CupriFace.Shell" Version="0.2.11" />
    <PackageReference Include="Silk.NET.SDL" Version="2.22.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Bantz.Core/Bantz.Core.csproj" />
    <ProjectReference Include="../Bantz.App/Bantz.App.csproj" />
  </ItemGroup>
</Project>
