<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Bantz</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Whisper.net" Version="1.9.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Bantz.Core/Bantz.Core.csproj" />
    <ProjectReference Include="../../external/CupriFace/src/CupriFace/CupriFace.csproj" />
    <ProjectReference Include="../../external/CupriFace/src/CupriFace.Binding.Gen/CupriFace.Binding.Gen.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../external/CupriFace/src/CupriFace.Resources.Gen/CupriFace.Resources.Gen.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <Import Project="../../external/CupriFace/src/CupriFace.Resources.targets" />
</Project>
